// Code generated by "stringer -type=stage -trimprefix stage"; DO NOT EDIT.

package mp3binder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stageInit-0]
	_ = x[stageBind-1]
	_ = x[stageCopyMetadata-2]
	_ = x[stageApplyMetadata-3]
	_ = x[stageBuildChapers-4]
	_ = x[stageWriteMetadata-5]
	_ = x[stageCombineId3AndAudio-6]
	_ = x[stageLastElement-7]
}

const _stage_name = "InitBindCopyMetadataApplyMetadataBuildChapersWriteMetadataCombineId3AndAudioLastElement"

var _stage_index = [...]uint8{0, 4, 8, 20, 33, 45, 58, 76, 87}

func (i stage) String() string {
	if i < 0 || i >= stage(len(_stage_index)-1) {
		return "stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _stage_name[_stage_index[i]:_stage_index[i+1]]
}
