// Code generated by "stringer -type=stage -trimprefix stage"; DO NOT EDIT.

package mp3binder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stageInit-0]
	_ = x[stageReadMetadata-1]
	_ = x[stageBind-2]
	_ = x[stageCopyMetadata-3]
	_ = x[stageBeforeWriteMetadata-4]
	_ = x[stageWriteMetadata-5]
	_ = x[stageLastElement-6]
}

const _stage_name = "InitReadMetadataBindCopyMetadataBeforeWriteMetadataWriteMetadataLastElement"

var _stage_index = [...]uint8{0, 4, 16, 20, 32, 51, 64, 75}

func (i stage) String() string {
	if i < 0 || i >= stage(len(_stage_index)-1) {
		return "stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _stage_name[_stage_index[i]:_stage_index[i+1]]
}
