name: Build
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.0-rc.1"
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Download Go modules
        run: |
          go mod download
          go mod verify
        env:
          GOPROXY: https://proxy.golang.org
      - name: Test
        run: task build-all
