name: Test, Build and release if tagged
on: [push]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [macos-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: ${{matrix.go-version}}
        id: go
      - name: install go
        run: |
          go install golang.org/dl/go1.18rc1@latest
          go1.18rc1 download
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@v2
      - name: Download Go modules
        run: |
          go1.18rc1 mod download
          go1.18rc1 mod verify
        env:
          GOPROXY: https://proxy.golang.org
      - name: Test
        run: task build-all
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.zip
          draft: true
