name: Build
on:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19]
        platform: [macos-latest]
      runs-on: ${{matrix.platform}}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v3
          with:
            go-version: ${{matrix.go-version}}
        - name: Install Task
          uses: arduino/setup-task@v1
        - name: Download Go modules
          run: |
            go mod download
            go mod verify
          env:
            GOPROXY: https://proxy.golang.org
        - name: Test
          run: task default:build
