name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go-version: ["stable"]
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        id: go
        with:
          go-version: ${{matrix.go-version}}

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Download Go modules
        run: |
          go mod download
          go mod verify
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build
        run: task default:build-all
