name: release

on: workflow_dispatch

jobs:
  release:
    name: Release

    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        go-version: [1.19]
        platform: [ubuntu-latest, windows-latest, macos-latest]
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}
          cache: true
          cache-dependency-path: go.sum

      - name: Install Task
        uses: arduino/setup-task@v1
      
      - name: Download Go modules
        run: |
          go mod download
          go mod verify
        env:
          GOPROXY: https://proxy.golang.org
      
      - name: Build
        run: task default:build-all
      
      - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
              draft: true
              generate_release_notes: true
              files: dist/*.zip
