name: Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: ${{matrix.go-version}}
        id: go
      - name: install go
        run: |
          go install golang.org/dl/go1.18beta2@latest
          go1.18beta2 download
      - name: Install Task
        uses: arduino/setup-task@v1
      - uses: actions/checkout@v2
      - name: Download Go modules
        run: |
          go1.18beta2 mod download
          go1.18beta2 mod verify
        env:
          GOPROXY: https://proxy.golang.org
      #- name: Test
      #  run: task test
